name: Build Project
on:
  workflow_call:
    outputs:
      build-folder:
        description: 'Path to built site'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-folder: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build site
        run: |
          cd v0.2.0
          npm install
          npm run build

      - name: Upload Pages Artifact
        id: upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: v0.2.0/dist
