name: Deploy Site
on:
  workflow_call:
    inputs:
      build-folder:
        description: 'Path to built site'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          folder: ${{ inputs.build-folder }}
