name: Pipeline
on:
    push:
      branches: [ "dev" ]   
    workflow_dispatch:

        # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v3
    call-workflow1:
        uses: ./.github/workflows/build-dist.yml
    call-workflow2:
        needs: call-workflow1
        uses: ./.github/workflows/deploy-site.yml